=== ownfloa/floapay-magento/etc/form-validation-fields/validator.xsd
<?xml version="1.0" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="config">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="1" maxOccurs="unbounded" name="fields" type="fieldsType" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="fieldsType">
        <xs:sequence>
            <xs:element minOccurs="1" maxOccurs="unbounded" name="field" type="fieldType" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="fieldType">
        <xs:all>
            <xs:element name="required"/>
            <xs:element name="pattern" minOccurs="0" type="xs:string"/>
            <xs:element minOccurs="0" name="choose" type="selectType"/>
            <xs:element minOccurs="0" name="required-if" type="requiredConditionType"/>
            <xs:element minOccurs="0" name="validator-method" type="xs:string"/>
            <xs:element minOccurs="1" name="invalid-message" type="xs:string"/>
            <xs:element minOccurs="0" name="js-validation-name" type="xs:string"/>
            <xs:element minOccurs="1" name="label" type="xs:string"/>
            <xs:element minOccurs="0" name="tooltip" type="xs:string"/>
        </xs:all>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="type" type="xs:string" use="required"/>
        <xs:attribute name="payment_code" type="xs:string" use="required"/>
        <xs:attribute name="class" type="xs:string"/>
        <xs:attribute name="style" type="xs:string"/>
    </xs:complexType>
    <xs:complexType name="selectType">
        <xs:sequence>
            <xs:element name="option" minOccurs="1" maxOccurs="unbounded" type="selectOptionType"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="selectOptionType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="value" type="xs:string">
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="requiredConditionType">
        <xs:attribute name="field" type="xs:string" use="required"/>
        <xs:attribute name="value" type="xs:string" use="required"/>
        <xs:attribute name="optional" type="xs:string"/>
    </xs:complexType>
</xs:schema>

=== ownfloa/floapay-magento/etc/form-validation-fields/country/it.xml
<?xml version="1.0" ?>
<!--
	/**
	* 2021 Floa BANK
	*
	* THE MIT LICENSE
	*
	* Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
	* documentation files (the "Software"), to deal in the Software without restriction, including without limitation
	* the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and
	* to permit persons to whom the Software is furnished to do so, subject to the following conditions:
	* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the
	* Software.
	*
	* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
	* WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
	* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
	* CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
	* IN THE SOFTWARE.
	*
	* @author    FLOA Bank
	* @copyright 2021 FLOA Bank
	* @license   https://opensource.org/licenses/MIT The MIT License
	*/
-->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../validator.xsd">
    <fields>
        <field class="civility" name="civility" type="select" payment_code="all">
            <label>Civility</label>
            <required>true</required>
            <choose>
                <option value="Mr">M.</option>
                <option value="Mrs">Mrs</option>
            </choose>
            <invalid-message>Civility is mandatory.</invalid-message>
        </field>
        <field class="nif" name="nationality_id" type="text" payment_code="all">
            <label>Tax identification number</label>
            <required>true</required>
            <pattern>/^([a-zA-Z]{6})+([0-9]{2})+([a-zA-Z]{1})+([0-9]{2})+([a-zA-Z]{1})+([0-9]{3})+([a-zA-Z]{1})$/</pattern>
            <invalid-message>Tax identification number is mandatory.</invalid-message>
            <js-validation-name>tax-code-custom</js-validation-name>
        </field>
        <field class="birthdate" name="birth_date" type="date" payment_code="all">
            <label>Your date of birth</label>
            <required>true</required>
            <validator-method>isMajorCustomer</validator-method>
            <invalid-message>Birth date is mandatory.</invalid-message>
        </field>
        <field class="phone"  name="phone_number" type="text" payment_code="all">
            <label>Phone number</label>
            <required>true</required>
            <pattern>/^([+])?\d{9,13}$/</pattern>
            <invalid-message>Please enter a valid phone number.</invalid-message>
            <js-validation-name>phone-custom</js-validation-name>
        </field>
        <field class="accept-data-collect" name="accept_data_collect" type="checkbox" payment_code="all">
            <label>By validating this information, you agree that your data will be used for the purpose of evaluating your eligibility for payment in installments.</label>
            <required>true</required>
            <invalid-message>To continue, you must agree to your personal data being processed by FLOA.</invalid-message>
            <validator-method>isDataCollectAccepted</validator-method>
            <tooltip>More information here.</tooltip>
        </field>
        <field class="accept-terms-conditions" name="accept_terms_conditions" type="checkbox" payment_code="all">
            <label>By validating your choice of payment, you have read and accept the general conditions of payment in installments of FLOA.</label>
            <required>true</required>
            <invalid-message>To continue, please accept the terms and conditions.</invalid-message>
            <validator-method>isTermsConditionsAccepted</validator-method>
            <tooltip>See here.</tooltip>
        </field>
    </fields>
</config>
